[book]
title = "Windows Kernel Anti-Cheat Development"
authors = ["Choi-Jungwoo"]
language = "zh-CN"

[output.html]
site-url = "/windows-kernel-anti-cheat-development/"
additional-css = ["theme/tables.css"]
